Repository AllenCellModeling/actk, pull requests merged in 2020-08, with the labels that each got.

#24 feature/check-input-csv
  actk/steps/standardize_fov_array/standardize_fov_array.py
  actk/tests/steps/test_standardize_fov_array.py
  scripts/download_test_data.py
Labels: bug, enhancement

#21 feature/revert-to-batched-map
  README.md
  actk/__init__.py
  actk/bin/all.py
  actk/steps/single_cell_features/single_cell_features.py
  actk/steps/single_cell_images/single_cell_images.py
  actk/steps/standardize_fov_array/standardize_fov_array.py
  setup.py
Labels: enhancement

#26 bugfix/required-fields
  actk/exceptions.py
  actk/steps/standardize_fov_array/standardize_fov_array.py
  actk/utils/dataset_utils.py
  scripts/download_aics_dataset.py
  setup.py
Labels: bug

#22 feature/add-custom-metadata-based-diagnostic-sheets
  actk/bin/all.py
  actk/constants.py
  actk/steps/__init__.py
  actk/steps/make_diagnostic_sheet/__init__.py
  actk/steps/make_diagnostic_sheet/make_diagnostic_sheet.py
  actk/tests/steps/test_make_diagnostic_sheet.py
Labels: enhancement

#25 feature/add-bbox-kwarg
  actk/steps/single_cell_images/single_cell_images.py
  actk/tests/steps/test_single_cell_images.py
Labels: enhancement

#27 admin/cleanup
  .gitignore
  README.md
  actk/bin/all.py
  actk/constants.py
  actk/steps/__init__.py
  actk/steps/make_diagnostic_sheet/make_diagnostic_sheet.py
  actk/steps/raw/__init__.py
  actk/steps/raw/raw.py
  actk/steps/single_cell_features/single_cell_features.py
  actk/steps/single_cell_images/single_cell_images.py
  actk/steps/standardize_fov_array/standardize_fov_array.py
  actk/tests/steps/test_standardize_fov_array.py
  actk/tests/utils/test_image_utils.py
  actk/utils/image_utils.py
  docs/dataset_fields.md
  scripts/download_aics_dataset.py
  scripts/download_test_data.py
  setup.py
Labels: admin, documentation, enhancement

#31 admin/merge-aligned-and-source-read-path
  actk/steps/make_diagnostic_sheet/make_diagnostic_sheet.py
  actk/steps/raw/raw.py
  actk/steps/single_cell_features/single_cell_features.py
  actk/steps/single_cell_images/single_cell_images.py
  actk/steps/standardize_fov_array/standardize_fov_array.py
  actk/tests/steps/test_single_cell_images.py
  actk/tests/utils/test_image_utils.py
  actk/utils/dataset_utils.py
  scripts/download_aics_dataset.py
  setup.py
Labels: admin

#32 admin/change-default-segmentation-ceiling-adjust
  actk/tests/utils/test_image_utils.py
  actk/utils/image_utils.py
Labels: admin
